name: Publish Docker image
on:
  release:
    types: [published]

  push:
   branches:
     - master

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set Environment Variables
        run: |
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yangzun/private-hugo-blog:latest
            yangzun/private-hugo-blog:1.0.${{ env.GITHUB_RUN_NUMBER }}
#       -
#         name: ssh pipelines
#         uses: cross-the-world/ssh-pipeline@master
#         env:
#           WELCOME: "ssh pipeline"
#         with:
#           host: ${{ secrets.BASE_HOST }}
#           user: ${{ secrets.BASE_USER }}
#           pass: ${{ secrets.BASE_PASS }}
#           port: ${{ secrets.BASE_PORT }}
#           connect_timeout: 10s
#           script: |
#             set +x
#             cd /data/docker-compose/blog/
#             set -x
#             cat docker-compose.yaml |yq e .services.blog.image -
#             yq e -i '.services.blog.image  = "yangzun/private-hugo-blog:1.0.${{ env.GITHUB_RUN_NUMBER }}"' docker-compose.yaml
#             docker-compose pull
#             docker-compose up -d
      -
        name: n2 ssh pipelines
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ziru.treesir.pub
          user: ${{ secrets.BASE_USER }}
          pass: ${{ secrets.BASE_PASS }}
          port: 2222	
          connect_timeout: 10s
          script: |
            set +x
            cd /data/git/argocd-projects/hugo-blog
            set -x
            git pull
            cat values.yaml |yq e .image.tag -
            yq e -i '.image.tag = "1.0.${{ env.GITHUB_RUN_NUMBER }}"' values.yaml
            if ! git diff-index --quiet HEAD --; then git status && git add . && git commit -m "helm values updated by ci pipeline in change-manifests task" && git push origin sit; else echo "no changes, git repository is up to date" ;fi
 
